import Head from 'next/head'
import Message from '../components/Message'
import { collection, orderBy, query } from 'firebase/firestore'
import { db } from '../utils/firebase'
import Link from 'next/link'
import { useCollection } from 'react-firebase-hooks/firestore'
import { MutatingDots } from 'react-loader-spinner'
import { TbMoodEmpty } from 'react-icons/tb'

export default function Home() {
  const collectionRef = collection(db, 'posts')
  const q = query(collectionRef, orderBy('timestamp', 'desc'))
  const [value, loading] = useCollection(q)

  return (
    <div>
      <Head>
        <title>Creative Minds</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='my-12 text-lg font-medium'>
        <h2>See what other people are saying</h2>
        {loading && (
          <MutatingDots
            height='100'
            width='100'
            color='#27bdec'
            secondaryColor='#31a0a6'
            radius='12.5'
            ariaLabel='mutating-dots-loading'
            visible={true}
          />
        )}
        {value?.empty && (
          <div className='mt-10 flex items-center gap-x-1 justify-center'>
            {' '}
            <TbMoodEmpty className='text-2xl' />
            <span>List of posts is empty</span>
          </div>
        )}
        {value?.docs.map(doc => (
          <Message key={doc.id} {...doc.data()}>
            <Link
              href={{
                pathname: `/${doc.id}`,
                query: {
                  ...doc.data(),
                  id: doc.id,
                  timestamp: doc.data().timestamp.seconds
                }
              }}
            >
              <button className='text-sm bg-slate-100 p-2 rounded-lg hover:shadow-md'>
                {doc.data().comments?.length > 0
                  ? doc.data().comments?.length
                  : 0}{' '}
                Comments
              </button>
            </Link>
          </Message>
        ))}
      </div>
    </div>
  )
}
